name: rick_and_morty_api
description: API wrapper for rickandmortyapi.com
version: 0.0.1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  http: ^0.13.4
  json_annotation: ^4.5.0

dev_dependencies:
  coverage: ^1.3.2
  flutter_lints: ^1.0.0
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
